stages:
  - build

build-job:
  stage: build
  tags:
    - iso
  script:
    - pacman -Syu --noconfirm skopeo umoci xorriso grub dosfstools squashfs-tools jq git python-click python-fasteners python-yaml
    - for image in arch-{gnome,plasma}; do ./iso-builder.sh "configs/${image}.yaml"; mv blendOS.iso ../"blendOS-${image}.iso"; done
    - echo $CI_COMMIT_SHA > version
    - for image in blendOS-arch-{gnome,plasma}; do sha256sum "${image}.iso" > "${image}.iso.sha256sum"; done
  artifacts:
    paths:
      - '*.iso'
      - version
      - '*.sha256sum'
